#!/bin/sh
#
# redis-start.sh: entrypoint wrapper for the redis service (DK-3, M7).
#
# Redis must require a password. This script:
#   1. refuses to start when SOCKBOWL_REDIS_PASSWORD is empty, or is a
#      CHANGE_ME placeholder or a well-known default (via check-secrets.sh);
#   2. writes requirepass, bind and maxmemory into a config file readable by the
#      redis user only, so the password never appears in argv or `ps`;
#   3. execs the image's own docker-entrypoint.sh, which still fixes /data
#      permissions, drops privileges to the redis user and loads the bundled
#      Search/JSON modules.
#
# Env
#   SOCKBOWL_REDIS_PASSWORD   required; characters limited to A-Z a-z 0-9 . _ ~ + = / -
#   SOCKBOWL_REDIS_BIND       bind addresses (default "127.0.0.1 -::1": loopback only)
#   SOCKBOWL_REDIS_MAXMEMORY  maxmemory (default 0 = unlimited), e.g. 128mb
#   ALLOW_INSECURE_DEFAULTS   true lets check-secrets.sh placeholders through (dev only)
#
# POSIX sh (the redis image's /bin/sh is dash).
set -eu

log() { echo "[redis-start] $*" >&2; }
die() { log "ERROR: $*"; exit 1; }

# check-secrets.sh exits the shell on an insecure value. SOCKBOWL_REDIS_PASSWORD
# is in its list.
# shellcheck source-path=SCRIPTDIR source=check-secrets.sh
. /check-secrets.sh

pw="${SOCKBOWL_REDIS_PASSWORD:-}"
if [ -z "$pw" ]; then
  # Dev-only escape: an explicitly EMPTY password under ALLOW_INSECURE_DEFAULTS
  # (docker-compose.dev.yml) runs without auth, loopback-bound, for app images
  # built before the apps learned SOCKBOWL_REDIS_PASSWORD. Unset in dev gets
  # the overlay's dev password instead; prod never gets here.
  [ "${ALLOW_INSECURE_DEFAULTS:-false}" = "true" ] \
    || die "SOCKBOWL_REDIS_PASSWORD is not set. Redis refuses to start without a password (DK-3). Set it in .env (docker-compose.dev.yml supplies a dev-only default)."
  log "WARNING: SOCKBOWL_REDIS_PASSWORD is empty; starting WITHOUT auth because ALLOW_INSECURE_DEFAULTS=true (dev only, never in production)"
fi
case "$pw" in
  *[!A-Za-z0-9._~+=/-]*)
    die "SOCKBOWL_REDIS_PASSWORD contains characters outside A-Z a-z 0-9 . _ ~ + = / - (they would need quoting in redis.conf and in client URLs). Generate one with: openssl rand -hex 32" ;;
esac

bind="${SOCKBOWL_REDIS_BIND:-127.0.0.1 -::1}"
case "$bind" in
  *[!0-9A-Fa-f.:*\ -]*|'') die "SOCKBOWL_REDIS_BIND must be a space-separated list of addresses (got '${bind}')" ;;
esac

maxmemory="${SOCKBOWL_REDIS_MAXMEMORY:-0}"
case "$maxmemory" in
  ''|*[!0-9a-zA-Z]*) die "SOCKBOWL_REDIS_MAXMEMORY must look like 0, 134217728 or 128mb (got '${maxmemory}')" ;;
esac

conf_dir=/run/sockbowl-redis
conf="${conf_dir}/redis.conf"
umask 077
mkdir -p "$conf_dir"
{
  echo "# Generated by redis-start.sh at container start; not persisted."
  echo "bind ${bind}"
  echo "protected-mode yes"
  [ -z "$pw" ] || echo "requirepass ${pw}"
  echo "maxmemory ${maxmemory}"
  # noeviction: an evicting policy could silently drop ban keys or live game
  # sessions. With noeviction a full Redis rejects writes instead, and the
  # limiters fail open on that (D12).
  echo "maxmemory-policy noeviction"
} >"$conf"

if [ -n "$pw" ]; then auth=required; else auth=OFF; fi
log "starting redis (bind: ${bind}; maxmemory: ${maxmemory}; auth: ${auth})"
# The image's entrypoint treats a first argument ending in .conf as the config
# file, chowns it (and its directory) to redis for reading, drops privileges
# and appends the --loadmodule flags.
unset pw
exec docker-entrypoint.sh redis-server "$conf"
